version: '2'

services:
  etcdkeeper:
    image: deltaprojects/etcdkeeper
    container_name: etcdkeeper
    ports:
      - 8081:8080
    networks:
      - local-net
    external_links:
      - etcd-singleton

networks:
  local-net:
    external: true
